version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: yes
permissions:
  - object: /usr/share/nginx/html
    owner: ubuntu
    group: ubuntu
    mode: 755
# hooks:
#   AfterInstall:
#     - location: deploy.sh
#       timeout: 60
#       runas: ubuntu
