export const HANDY_PARTY_ROUTE_AREA = [
  '동북권',
  '서북권',
  '중심권',
  '성동.광진권',
  '강서권',
  '서남권',
  '동남권',
  '수원',
  '성남',
  '고양',
  '부평',
  '광명',
  '동탄',
  '안양',
  '안산',
  '하남',
  '남양주',
  '용인',
  '시흥',
  '파주',
  '평택',
] as const;
export type HandyPartyRouteArea = (typeof HANDY_PARTY_ROUTE_AREA)[number];

export const HANDY_PARTY_AREA_TO_ADDRESS: Record<
  HandyPartyRouteArea,
  { sido: string; gungu: string[]; dong?: string[] }
> = {
  동북권: { sido: '서울', gungu: ['도봉구', '강북구', '노원구', '성북구'] },
  서북권: { sido: '서울', gungu: ['은평구', '서대문구', '마포구'] },
  중심권: { sido: '서울', gungu: ['중구', '종로구', '용산구'] },
  '성동.광진권': {
    sido: '서울',
    gungu: ['중랑구', '동대문구', '성동구', '광진구'],
  },
  강서권: { sido: '서울', gungu: ['강서구', '양천구', '구로구'] },
  서남권: { sido: '서울', gungu: ['영등포구', '동작구', '관악구', '금천구'] },
  동남권: { sido: '서울', gungu: ['서초구', '강남구', '송파구', '강동구'] },
  수원: { sido: '경기', gungu: ['수원시'] },
  성남: { sido: '경기', gungu: ['성남시'] },
  고양: { sido: '경기', gungu: ['고양시'] },
  부평: { sido: '인천', gungu: ['부평구'] },
  광명: { sido: '경기', gungu: ['광명시'] },
  동탄: {
    sido: '경기',
    gungu: ['화성시'],
    dong: [
      '능동',
      '석우동',
      '반송동',
      '영천동',
      '오산동',
      '청계동',
      '목동',
      '산척동',
      '송동',
      '방교동',
      '장지동',
      '신동',
    ],
  },
  안양: { sido: '경기', gungu: ['안양시'] },
  안산: { sido: '경기', gungu: ['안산시'] },
  하남: { sido: '경기', gungu: ['하남시'] },
  남양주: { sido: '경기', gungu: ['남양주시'] },
  용인: {
    sido: '경기',
    gungu: ['용인시'],
    dong: ['수지구', '기흥구'],
  },
  시흥: { sido: '경기', gungu: ['시흥시'] },
  파주: {
    sido: '경기',
    gungu: ['파주시'],
    dong: [
      '문발동',
      '동패동',
      '다율동',
      '목동동',
      '당하동',
      '와동동',
      '야당동',
    ],
  },
  평택: { sido: '경기', gungu: ['평택시'] },
} as const;
