import type { Metadata } from 'next';
import './globals.css';
import '@/app/fonts/pretendard/font.css';
import DeadZone from '@/components/DeadZone';
import ToastContainer from '@/components/ToastContainer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="overflow-hidden">
        <DeadZone>
          {children}
          <ToastContainer />
        </DeadZone>
      </body>
    </html>
  );
}
