import type { Metadata } from 'next';
import './globals.css';
import '@/app/fonts/pretendard/font.css';
import Provider from '@/components/Provider';
import { ReactNode } from 'react';
import ToastContainer from '@/components/toast-container/ToastContainer';
import PortalContainer from '@/components/portal-container/PortalContainer';

export const metadata: Metadata = {
  title: '핸디버스',
  description: 'Generated by create next app',
  formatDetection: {
    telephone: false,
    date: false,
    address: false,
    email: false,
  },
};

const jsonLd = {
  '@context': 'https://www.handybus.co.kr',
  '@type': 'WebSite',
  name: '핸디버스',
  description:
    '공연/행사 수요응답형 모빌리티 플랫폼, 핸디버스를 통해 내 지역에서부터 목적지까지 “내가 원하는” 셔틀을 이용할 수 있어요. 콘서트, 공연, 행사 등 다양한 이동의 여정에서 핸디버스를 만나보세요!',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Provider>
          {children}
          <PortalContainer />
          <ToastContainer />
        </Provider>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </body>
    </html>
  );
}
