export const STATIC_REVIEWS = [
  {
    reviewId: 'review-001',
    reservationId: 'rsv-12345',
    rating: 5,
    overallRating: 5,
    serviceRating: 5,
    rideRating: 5,
    recommendToOther: true,
    content:
      '핸디 버스 차 대절은 이번이 두번째인데 일반적인 고석버스와는 다른 크고 편안한 좌석과 기사님도 너무 친절하셨고 할인 이벤트도 쉽게 참여할 수 있는게 큰 장점이었어요 다음에도 또 이용할 생각입니다 💚',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-08-04',
    updatedAt: '2024-08-04',
    userId: 'user-789001',
    userNickname: '맠쿨럭',
    userProfileImage: null,
    eventId: 'evt-127001',
    eventName: '2024 NCT 127 8th ANNIVERSARY FANMEETING <8ECRET INVITATION>',
    eventType: 'CONCERT' as const,
    eventLocationName: '잠실실내체육관',
    eventImageUrl:
      'https://handybus.co.kr/images/events/nct127-anniversary.jpg',
    eventArtists: ['NCT 127'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-1-1.png',
        status: 'ACTIVE' as const,
      },
      {
        imageUrl: '/images/reviews/review-1-2.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-002',
    reservationId: 'rsv-12346',
    rating: 4,
    overallRating: 4,
    serviceRating: 5,
    rideRating: 3,
    recommendToOther: true,
    content:
      '두번째 이용인데 기사님이 너무 친절하셨고 덕분에 막차시간 신경 쓸 필요도 없이 대전까지 정말 편하게 올 수 있었습니다',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-08-03',
    updatedAt: '2024-08-03',
    userId: 'user-789002',
    userNickname: '연승현',
    userProfileImage: null,
    eventId: 'evt-127002',
    eventName: '2024 NCT 127 8th ANNIVERSARY FANMEETING <8ECRET INVITATION>',
    eventType: 'CONCERT' as const,
    eventLocationName: '잠실실내체육관',
    eventImageUrl:
      'https://handybus.co.kr/images/events/nct127-anniversary.jpg',
    eventArtists: ['NCT 127'],
    reviewImages: [],
  },
  {
    reviewId: 'review-003',
    reservationId: 'rsv-12347',
    rating: 5,
    overallRating: 5,
    serviceRating: 4,
    rideRating: 5,
    recommendToOther: true,
    content: '라이즈 팬콘때 진짜 편안하고 빠르게 잘 다녀왔어요 🧡',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-05-04',
    updatedAt: '2024-05-04',
    userId: 'user-789003',
    userNickname: 'danaas2',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789003.jpg',
    eventId: 'evt-riize001',
    eventName: "2024 RIIZE FAN-CON TOUR 'RIIZING DAY'",
    eventType: 'FANMEETING' as const,
    eventLocationName: '잠실실내체육관',
    eventImageUrl: 'https://handybus.co.kr/images/events/riize-fancon.jpg',
    eventArtists: ['RIIZE'],
    reviewImages: [],
  },
  {
    reviewId: 'review-004',
    reservationId: 'rsv-12348',
    rating: 3,
    overallRating: 3,
    serviceRating: 4,
    rideRating: 2,
    recommendToOther: true,
    content:
      '캐럿랜드 차대절 후기!\n 트친이 알려줘서 타고왔는데 가격도 꽤 괜찮았고 버스도 우등버스라 편했하구 엄청 조용해서 편하게 갔다왔어요!\n 같이 탑승한 부총대님이 친절하게 인솔해주셔서 잘 다녀왔어요-!!',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-07-23',
    updatedAt: '2024-07-24',
    userId: 'user-789004',
    userNickname: '묘다',
    userProfileImage: null,
    eventId: 'evt-svt001',
    eventName: '2024 SVT 8TH FAN MEETING SEVENTEEN in CARAT LAND',
    eventType: 'FANMEETING' as const,
    eventLocationName: '고척스카이돔',
    eventImageUrl:
      'https://handybus.co.kr/images/events/seventeen-caratland.jpg',
    eventArtists: ['SEVENTEEN'],
    reviewImages: [],
  },
  {
    reviewId: 'review-005',
    reservationId: 'rsv-12349',
    rating: 4,
    overallRating: 4,
    serviceRating: 3,
    rideRating: 5,
    recommendToOther: true,
    content:
      '전에 다른 대절을 이용했을땐 일반 관광버스가 와서 조금은 불편했는데 우등버스로 운행해주셔서 편안하게 이동할 수 있었습니다 :D',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-07-24',
    updatedAt: '2024-07-25',
    userId: 'user-789005',
    userNickname: 'seungjin',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789005.jpg',
    eventId: 'evt-svt001',
    eventName: '2024 SVT 8TH FAN MEETING SEVENTEEN in CARAT LAND',
    eventType: 'FANMEETING' as const,
    eventLocationName: '고척스카이돔',
    eventImageUrl:
      'https://handybus.co.kr/images/events/seventeen-caratland.jpg',
    eventArtists: ['SEVENTEEN'],
    reviewImages: [],
  },
  {
    reviewId: 'review-006',
    reservationId: 'rsv-12350',
    rating: 5,
    overallRating: 5,
    serviceRating: 5,
    rideRating: 5,
    recommendToOther: true,
    content:
      '인천콘때부터 핸디버스 만 타요ㅋㅋㅋㅋ 자방럿에겐 제일 좋은 방법.. 사랑해요 핸디버스',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-10-12',
    updatedAt: '2024-10-12',
    userId: 'user-789006',
    userNickname: 'tanily',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789006.jpg',
    eventId: 'evt-svt002',
    eventName: 'SEVENTEEN [RIGHT HERE] WORLD TOUR IN GOYANG',
    eventType: 'CONCERT' as const,
    eventLocationName: '고양종합운동장',
    eventImageUrl:
      'https://handybus.co.kr/images/events/seventeen-righthere.jpg',
    eventArtists: ['SEVENTEEN'],
    reviewImages: [],
  },
  {
    reviewId: 'review-007',
    reservationId: 'rsv-12351',
    rating: 2,
    overallRating: 2,
    serviceRating: 4,
    rideRating: 1,
    recommendToOther: false,
    content:
      '공지사항을 꼼꼼하고 자세하게 알려주셔서 항상 믿고 탈 수 있습니다 특히 버스 기사남께서 말로 다 표현 못할정도로 친절하세요',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-04-27',
    updatedAt: '2024-04-28',
    userId: 'user-789007',
    userNickname: '심진희',
    userProfileImage: null,
    eventId: 'evt-svt003',
    eventName: "SEVENTEEN TOUR 'FOLLOW' AGAIN TO SEOUL",
    eventType: 'CONCERT' as const,
    eventLocationName: '서울월드컵경기장',
    eventImageUrl: 'https://handybus.co.kr/images/events/seventeen-follow.jpg',
    eventArtists: ['SEVENTEEN'],
    reviewImages: [],
  },
  {
    reviewId: 'review-008',
    reservationId: 'rsv-12352',
    rating: 1,
    overallRating: 1,
    serviceRating: 2,
    rideRating: 1,
    recommendToOther: false,
    content:
      '기사님도 친절하고 유쾌하셔서 버스타는동안 너무 편안하게 갔다왔습니다! 다음에도 이용할 수 있으면 꼭 다시 이용할게요!!❤️',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-05-04',
    updatedAt: '2024-05-05',
    userId: 'user-789008',
    userNickname: 'minjoo',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789008.jpg',
    eventId: 'evt-nctd001',
    eventName: '2024 NCT DREAM WORLD TOUR <THE DREAM SHOW 3>',
    eventType: 'CONCERT' as const,
    eventLocationName: '고척스카이돔',
    eventImageUrl:
      'https://handybus.co.kr/images/events/nctdream-dreamshow.jpg',
    eventArtists: ['NCT DREAM'],
    reviewImages: [],
  },
  {
    reviewId: 'review-009',
    reservationId: 'rsv-12353',
    rating: 5,
    overallRating: 5,
    serviceRating: 5,
    rideRating: 4,
    recommendToOther: true,
    content:
      '지방럿 항상 가기 너무 힘든데 핸디버스 덕분에 너무 편하게 다녀왔어요!!',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-03-03',
    updatedAt: '2024-03-03',
    userId: 'user-789009',
    userNickname: 'heejin',
    userProfileImage: null,
    eventId: 'evt-iu001',
    eventName: '<2024 IU HEREH WORLD TOUR CONCERT [H.E.R.] 콘서트>',
    eventType: 'CONCERT' as const,
    eventLocationName: 'KSPO DOME',
    eventImageUrl: 'https://handybus.co.kr/images/events/iu-her.jpg',
    eventArtists: ['아이유'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-9.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-010',
    reservationId: 'rsv-12354',
    rating: 3,
    overallRating: 3,
    serviceRating: 4,
    rideRating: 3,
    recommendToOther: true,
    content: '아이유 콘서트 때 처음 이용해봤는데 너무 편하고 좋았어요!',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-10',
    userId: 'user-789010',
    userNickname: 'yongjin',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789010.jpg',
    eventId: 'evt-iu001',
    eventName: '<2024 IU HEREH WORLD TOUR CONCERT [H.E.R.] 콘서트>',
    eventType: 'CONCERT' as const,
    eventLocationName: 'KSPO DOME',
    eventImageUrl: 'https://handybus.co.kr/images/events/iu-her.jpg',
    eventArtists: ['아이유'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-10.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-011',
    reservationId: 'rsv-12355',
    rating: 4,
    overallRating: 4,
    serviceRating: 5,
    rideRating: 3,
    recommendToOther: true,
    content:
      '지방러들의 빛... 기사 분도 너무 친절하시고 총대 맡아주신 분도 너무 잘 설명해주셔서 편하게 다녀왔습니다 💛',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-02-23',
    updatedAt: '2024-02-24',
    userId: 'user-789011',
    userNickname: 'crealiy',
    userProfileImage: null,
    eventId: 'evt-enh001',
    eventName: "ENHYPEN WORLD TOUR 'FATE PLUS' IN SEOUL",
    eventType: 'CONCERT' as const,
    eventLocationName: 'KSPO DOME',
    eventImageUrl: 'https://handybus.co.kr/images/events/enhypen-fateplus.jpg',
    eventArtists: ['ENHYPEN'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-11.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-012',
    reservationId: 'rsv-12356',
    rating: 5,
    overallRating: 5,
    serviceRating: 5,
    rideRating: 5,
    recommendToOther: true,
    content: '다음에도 꼭 열어주세요!! 🥺',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-02-23',
    updatedAt: '2024-02-23',
    userId: 'user-789012',
    userNickname: 'beliveall',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789012.jpg',
    eventId: 'evt-enh001',
    eventName: "ENHYPEN WORLD TOUR 'FATE PLUS' IN SEOUL",
    eventType: 'CONCERT' as const,
    eventLocationName: 'KSPO DOME',
    eventImageUrl: 'https://handybus.co.kr/images/events/enhypen-fateplus.jpg',
    eventArtists: ['ENHYPEN'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-12.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-013',
    reservationId: 'rsv-12357',
    rating: 2,
    overallRating: 2,
    serviceRating: 3,
    rideRating: 2,
    recommendToOther: false,
    content:
      '버스가 우등버스라 진짜 편했어요! 다음 콘서트 때도 이용할 생각입니당',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-09-21',
    updatedAt: '2024-09-21',
    userId: 'user-789013',
    userNickname: 'lilac',
    userProfileImage: null,
    eventId: 'evt-iu002',
    eventName: '<2024 IU HEREH WORLD TOUR CONCERT [H.E.R.] 앵콜 콘서트>',
    eventType: 'CONCERT' as const,
    eventLocationName: '서울월드컵경기장',
    eventImageUrl: 'https://handybus.co.kr/images/events/iu-her-encore.jpg',
    eventArtists: ['아이유'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-13.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
  {
    reviewId: 'review-014',
    reservationId: 'rsv-12358',
    rating: 1,
    overallRating: 1,
    serviceRating: 1,
    rideRating: 2,
    recommendToOther: false,
    content: '핸디버스 덕분에 집 앞에서 타고 왔어요! 너무 편하고 좋아요',
    reviewStatus: 'ACTIVE' as const,
    createdAt: '2024-09-22',
    updatedAt: '2024-09-23',
    userId: 'user-789014',
    userNickname: 'aimin',
    userProfileImage: 'https://handybus.co.kr/images/profiles/user-789014.jpg',
    eventId: 'evt-iu002',
    eventName: '<2024 IU HEREH WORLD TOUR CONCERT [H.E.R.] 앵콜 콘서트>',
    eventType: 'CONCERT' as const,
    eventLocationName: '서울월드컵경기장',
    eventImageUrl: 'https://handybus.co.kr/images/events/iu-her-encore.jpg',
    eventArtists: ['아이유'],
    reviewImages: [
      {
        imageUrl: '/images/reviews/review-14.png',
        status: 'ACTIVE' as const,
      },
    ],
  },
];
