name: PR Checker

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read

jobs:
  pr-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Information
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            design
            fix
            hotfix
            comment
            docs
            style
            refactor
            perf
            test
            init
            build
            ci
            chore
            rename
            remove
            revert
            release
          requireScope: false
          subjectPattern: ^([A-Za-z가-힣].+|release)$
          subjectPatternError: |
            The subject must start with a letter or a Korean character and not end with a period.
          wip: false
          validateSingleCommit: false
